### ISSUE TITLE
feat: Finish function that already started

### ISSUE THREAD

**Issue by maxcodefaster** [robingenz/capacitor-background-task#17]
**Is your feature request related to a problem? Please describe:**

If i start a progress, let's say an upload function already before the on exit event. How would the logic be to continue this function?

**Comment by robingenz** [comment]
Hi @maxcodefaster,
thank you for your request.

This would be an extremely simple example:
```js
import { App } from '@capacitor/app';
import { BackgroundTask } from '@robingenz/capacitor-background-task';

const startUpload = () => {
  return new Promise<void>(resolve => {
    resolve();
  });
};

const startUploadPromise = startUpload();

App.addListener('appStateChange', async ({ isActive }) => {
  if (isActive) {
    return;
  }
  // The app state has been changed to inactive.
  // Start the background task by calling `beforeExit`.
  const taskId = await BackgroundTask.beforeExit(async () => {
    await startUploadPromise;
    // Finish the background task as soon as everything is done.
    BackgroundTask.finish({ taskId });
  });
});
```

You just have to call `beforeExit` as soon as the app is moved to the background and then call `finish`.

But please note: The task should be completed in less than 30 seconds. An upload can also take longer depending on the network connection, so this plugin is not really suitable for this. There are special APIs on iOS and Android that should be used for this. Unfortunately, no Capacitor plugin exists for these APIs as far as I know.
