### ISSUE TITLE
feat: How can i keep listen to bluetooth data?

### ISSUE THREAD

**Issue by Saqib92** [robingenz/capacitor-background-task#21]
**Is your feature request related to a problem? Please describe:**
I have a scenario where i have bluetooth sensor connected to my application. I am receiving continues data from bluetooth. My issue is when application go to background i want to keep listen to that data on both platforms android / ios. 

**Describe the solution you'd like:**
keep my bluetooth listener active in background mode to receive data.

**Describe alternatives you've considered:**
as per this Plugin [cordova-plugin-background-mode](https://github.com/katzer/cordova-plugin-background-mode) it says _"perform infinite background execution"_ 

**Additional context:**
I am using cordova-pluign-media-capture to record videos. but when i open camera application goes into background so i want to listen to Bluetooth data in background.

**Comment by robingenz** [comment]
Hi @Saqib92,
this plugin is used to run short background tasks (30 seconds) every 15 minutes.
So your use case is out-of-scope.
For this reason I am closing this issue.

My tip: For Bluetooth connections in the background, a Foreground Service is often used on Android (the https://github.com/katzer/cordova-plugin-background-mode plugin can do this, there is no Capacitor variant yet) and on iOS this is supported by the CoreBluetooth Library (see [Apple docs](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html)). So on iOS this should be supported by your Bluetooth plugin.

**Comment by Saqib92** [comment]
> Hi @Saqib92, this plugin is used to run short background tasks (30 seconds) every 15 minutes. So your use case is out-of-scope. For this reason I am closing this issue.
> 
> My tip: For Bluetooth connections in the background, a Foreground Service is often used on Android (the https://github.com/katzer/cordova-plugin-background-mode plugin can do this, there is no Capacitor variant yet) and on iOS this is supported by the CoreBluetooth Library (see [Apple docs](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html)). So on iOS this should be supported by your Bluetooth plugin.

Thanks for for fast response and guiding to right direction. Will take a look.
